version: '3.4'

services:
    www.keesz.int:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=44314
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/keesz-dev.pfx
            - ASPNETCORE_Kestrel__Certificates__Default__Password=Overdekop01
        ports:
            - '53600:80'
            - '53700:443'
        volumes:
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    api.keesz.int:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=44398
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/keesz-dev.pfx
            - ASPNETCORE_Kestrel__Certificates__Default__Password=Overdekop01
        ports:
            - '54600:80'
            - '54700:443'
        volumes:
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    game.keesz.int:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=44338
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/keesz-dev.pfx
            - ASPNETCORE_Kestrel__Certificates__Default__Password=Overdekop01
        ports:
            - '54603:80'
            - '54703:443'
        volumes:
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    connect.keesz.int:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=44338
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/keesz-dev.pfx
            - ASPNETCORE_Kestrel__Certificates__Default__Password=Overdekop01
        ports:
            - '54602:80'
            - '54702:443'
        volumes:
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    live.keesz.int:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=44338
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/keesz-dev.pfx
            - ASPNETCORE_Kestrel__Certificates__Default__Password=Overdekop01
        ports:
            - '54604:80'
            - '54704:443'
        volumes:
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

#    identity.keesz.int:
#        environment:
#            - ASPNETCORE_ENVIRONMENT=Development
#            - ASPNETCORE_URLS=https://+:443;http://+:80
#            - ASPNETCORE_HTTPS_PORT=44306
#            - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/keesz-dev.pfx
#            - ASPNETCORE_Kestrel__Certificates__Default__Password=Overdekop01
#        ports:
#            - '54601:80'
#            - '54701:443'
#        volumes:
#            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
#            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
#